src/Entity/Client.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Blameable\Traits\BlameableEntity;
use Gedmo\IpTraceable\Traits\IpTraceableEntity;
use Gedmo\SoftDeleteable\Traits\SoftDeleteableEntity;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ClientRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Client
{
    const PROSPECT=100;
    const CURRENT=200;
    const ON_HOLD=300;

    use TimestampableEntity;
    use SoftDeleteableEntity;
    use BlameableEntity;
    use IpTraceableEntity;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $mobile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $pays='France';

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $code_postal;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $status=self::PROSPECT;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $civilite;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Comptes", fetch="EAGER", mappedBy="compte_client_id")
     */
    private $comptes;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", fetch="EAGER", mappedBy="client", cascade={"persist", "remove"})
     */
    private $user;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $has_cb;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $has_chequier;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Demandes", mappedBy="client")
     */
    private $demandes;

    private $has_compte_epargne;
    private $has_compte_joint;
    private $has_decouvert_autorise;
    private $compte_courant;
    private $compte_joint;
    private $compte_epargne;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Beneficiaires", mappedBy="Client")
     */
    private $beneficiaires;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Chequiers", mappedBy="Client")
     */
    private $chequiers;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CartesBancaires", mappedBy="Client")
     */
    private $cartesBancaires;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $send_sms_notifications;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_naissance;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Agences", inversedBy="clients")
     */
    private $Agence;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function __construct()
    {
        $this->has_cb = false;
        $this->has_chequier = false;
        $this->setCreatedAt(new \DateTime());
        $this->comptes = new ArrayCollection();
        $this->demandes = new ArrayCollection();
        $this->operations = new ArrayCollection();
        //$this->setCreatedBy();

        $this->setHasCompteJoint(false);
        $this->setHasCompteEpargne(false);
        $this->setHasDecouvertAutorise(false);

        /*if ($this->id)
        {
            $comptes = $this->getComptes();
            foreach ($comptes as $compte)
            {
                $type_compte = $compte->getType();
                $nb_types_found = 0;
                switch($type_compte)
                {
                    case Comptes::COMPTE_JOINT:
                        $nb_types_found++;
                        $this->setHasCompteJoint(true);
                        break;

                    case Comptes::COMPTE_EPARGNE:
                        $nb_types_found++;
                        $this->setHasCompteEpargne(true);
                        break;

                    case Comptes::COMPTE_COURANT:
                        if ($compte->getDecouvertAutorise() == true)
                        {
                            $this->setHasDecouvertAutorise(true);
                        }
                        break;
                }

                if ($nb_types_found >= 2)
                {
                    break;
                }
            }
        }*/
        $this->beneficiaires = new ArrayCollection();
        $this->chequiers = new ArrayCollection();
        $this->cartesBancaires = new ArrayCollection();
    }

    /** @ORM\PostLoad() */
    public function doOnPostLoad()
    {
        $comptes = $this->getComptes();
        foreach ($comptes as $compte)
        {
            $type_compte = $compte->getType();
            $nb_types_found = 0;
            switch($type_compte)
            {
                case Comptes::COMPTE_JOINT:
                    $nb_types_found++;
                    $this->setHasCompteJoint(true);
                    $this->setCompteJoint($compte);
                    break;

                case Comptes::COMPTE_EPARGNE:
                    $nb_types_found++;
                    $this->setHasCompteEpargne(true);
                    $this->setCompteEpargne($compte);
                    break;

                case Comptes::COMPTE_COURANT:
                    $this->setCompteCourant($compte);
                    if ($compte->getDecouvertAutorise() == true)
                    {
                        $this->setHasDecouvertAutorise(true);
                    }
                    break;
            }

            if ($nb_types_found >= 2)
            {
                break;
            }
        }

        $chequiers = $this->getChequiers();
        if (count($chequiers))
        {
            $this->setHasChequier(true);
        }

        $cbs = $this->getCartesBancaires();
        if (count($cbs))
        {
            $this->setHasCb(true);
        }
    }

    public function getHasCompteEpargne(): ?bool
    {
        return $this->has_compte_epargne;
    }
    private function setHasCompteEpargne(?bool $has_compte_epargne): self
    {
        $this->has_compte_epargne = $has_compte_epargne;
        return $this;
    }

    public function getHasCompteJoint(): ?bool
    {
        return $this->has_compte_joint;
    }
    private function setHasCompteJoint(?bool $has_compte_joint): self
    {
        $this->has_compte_joint = $has_compte_joint;
        return $this;
    }

    public function getHasDecouvertAutorise(): ?bool
    {
        return $this->has_decouvert_autorise;
    }
    private function setHasDecouvertAutorise(?bool $has_decouvert_autorise): self
    {
        $this->has_decouvert_autorise= $has_decouvert_autorise;
        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getMobile(): ?string
    {
        return $this->mobile;
    }

    public function setMobile(?string $mobile): self
    {
        $this->mobile = $mobile;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(?string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(?string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(?int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCivilite(): ?string
    {
        return $this->civilite;
    }

    public function setCivilite(?string $civilite): self
    {
        $this->civilite = $civilite;

        return $this;
    }

    public function setCompteEpargne(?Comptes $compte): self
    {
        $this->compte_epargne = $compte;
        return $this;
    }
    public function getCompteEpargne(): ?Comptes
    {
        if ($this->compte_epargne) {
            return $this->compte_epargne;
        } else {
            foreach ($this->getComptes() as $compte) {
                if ($compte->getType() == Comptes::COMPTE_EPARGNE) {
                    $this->setCompteEpargne($compte);
                    break;
                }
            }
        }
    }

    public function setCompteJoint(?Comptes $compte): self
    {
        $this->compte_joint = $compte;
        return $this;
    }

src/Entity/Comptes.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Blameable\Traits\BlameableEntity;
use Gedmo\IpTraceable\Traits\IpTraceableEntity;
use Gedmo\SoftDeleteable\Traits\SoftDeleteableEntity;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ComptesRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Comptes
{
    use IpTraceableEntity;
    use BlameableEntity;
    use SoftDeleteableEntity;
    use TimestampableEntity;

    const COMPTE_COURANT = "COMPTE_COURANT";
    const COMPTE_EPARGNE = "COMPTE_EPARGNE";
    const COMPTE_JOINT = "COMPTE_JOINT";
    const COMPTE_AGENCE = "COMPTE_AGENCE";
    const COMPTE_BANQUE = "COMPTE_BANQUE";
    const COMPTE_BANK = "COMPTE_BANK";

    const COMPTES_LABELS = [
        self::COMPTE_COURANT => "Compte courant",
        self::COMPTE_EPARGNE => "Compte épargne",
        self::COMPTE_JOINT => "Compte joint",
        self::COMPTE_AGENCE => "Compte agence",
        self::COMPTE_BANQUE => "Compte banque",
        self::COMPTE_BANK => "Compte banque",
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", options={"unsigned"=true}, columnDefinition="INT(11) UNSIGNED ZEROFILL", nullable=true)
     */
    private $num_compte;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $type;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $solde;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $decouvert_autorise;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $decouvert_maximum;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Agences", fetch="EAGER", inversedBy="comptes")
     */
    private $agence_id;


    /**
     * @ORM\Column(type="integer", options={"unsigned"=true}, columnDefinition="INT(2) UNSIGNED ZEROFILL", nullable=true)
     */
    private $cle_rib;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $iban;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Client", fetch="EAGER", inversedBy="comptes")
     */
    private $compte_client_id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CartesBancaires", mappedBy="Compte")
     */
    private $cartesBancaires;

    public function __construct()
    {
        $this->compte_client_id = new ArrayCollection();
        $this->decouvert_autorise = false;
        $this->decouvert_maximum = 0;
        $this->solde = 0;
        $this->cartesBancaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumCompte(): ?int
    {
        return $this->num_compte;
    }

    public function setNumCompte(?int $num_compte): self
    {
        $this->num_compte = $num_compte;
        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function getTypeLbl(): ?string
    {
        return self::COMPTES_LABELS[$this->type];
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getCleRib(): ?int
    {
        return $this->cle_rib;
    }

    public function setCleRib(?int $cle_rib): self
    {
        $this->cle_rib = $cle_rib;
        return $this;
    }

    public function getIban(): ?string
    {
        return $this->iban;
    }

    public function setIban(?string $iban): self
    {
        $this->iban = $iban;

        return $this;
    }

    public function getSolde(): ?float
    {
        return $this->solde;
    }

    public function setSolde(?float $solde): self
    {
        $this->solde = $solde;

        return $this;
    }

    public function getDecouvertAutorise(): ?bool
    {
        return $this->decouvert_autorise;
    }

    public function setDecouvertAutorise(?bool $decouvert_autorise): self
    {
        $this->decouvert_autorise = $decouvert_autorise;

        return $this;
    }

    public function getDecouvertMaximum(): ?int
    {
        return $this->decouvert_maximum;
    }

    public function setDecouvertMaximum(?int $decouvert_maximum): self
    {
        $this->decouvert_maximum = $decouvert_maximum;

        return $this;
    }

    public function getAgenceId(): ?Agences
    {
        return $this->agence_id;
    }

    public function setAgenceId(?Agences $agence_id): self
    {
        $this->agence_id = $agence_id;

        return $this;
    }

    /**
     * @return Collection|Client[]
     */
    public function getCompteClientId(): Collection
    {
        return $this->compte_client_id;
    }

    public function addCompteClientId(Client $compteClientId): self
    {
        if (!$this->compte_client_id->contains($compteClientId)) {
            $this->compte_client_id[] = $compteClientId;
        }

        return $this;
    }

    public function removeCompteClientId(Client $compteClientId): self
    {
        if ($this->compte_client_id->contains($compteClientId)) {
            $this->compte_client_id->removeElement($compteClientId);
        }

        return $this;
    }

    /**
     * @return Collection|CartesBancaires[]
     */
    public function getCartesBancaires(): Collection
    {
        return $this->cartesBancaires;
    }

    public function addCartesBancaire(CartesBancaires $cartesBancaire): self
    {
        if (!$this->cartesBancaires->contains($cartesBancaire)) {
            $this->cartesBancaires[] = $cartesBancaire;
            $cartesBancaire->setCompte($this);
        }

        return $this;
    }

    public function removeCartesBancaire(CartesBancaires $cartesBancaire): self
    {
        if ($this->cartesBancaires->contains($cartesBancaire)) {
            $this->cartesBancaires->removeElement($cartesBancaire);
            // set the owning side to null (unless already changed)
            if ($cartesBancaire->getCompte() === $this) {
                $cartesBancaire->setCompte(null);
            }
        }

        return $this;
    }
}

templates/backoffice/bdd.html.twig
{% extends 'backoffice/base.html.twig' %}

{% block title %}Backoffice Banque Dauphine{% endblock %}

{% block navbar %}
    {% include 'backoffice/navbar_authenticated.html.twig' %}
{% endblock %}

{% block body %}

    <div class="container-fluid" style="padding-top: 55px;">
        YO
    </div>

{% endblock %}

templates/backoffice/comptes.html.twig
{% extends 'backoffice/base.html.twig' %}

{% block title %}Backoffice Banque Dauphine{% endblock %}

{% block navbar %}
    {% include 'backoffice/navbar_authenticated.html.twig' %}
{% endblock %}

{% block body %}

    <div class="container-fluid" style="padding-top: 55px;">
        {#{{ dump(clients) }}#}
        <table id="all_clients" class="table table-striped " cellspacing="0" style="width: 100%;">
            <thead>
                <tr>
                    <th></th>{# icon for row details #}
                    <th>Opérations</th>{# hidden , column just to host datas #}
                    <th>Prénom</th>
                    <th>Nom</th>
                    <th>Email</th>
                    <th>Code postal</th>
                    <th>Ville</th>
                    <th>Comptes</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
            {% for client in clients %}
                {% set _operations = [] %}
                {% for _operation in client.operations %}
                    {% set _montant = _operation.montant ~ ' €' %}
                    {% set _compte_emetteur = _operation.compteEmetteur %}
                    {% if _compte_emetteur.iban is defined and _montant < 0 %}
                        {% set _iban = _compte_emetteur.iban %}
                    {% else %}
                        {% set _iban = '' %}
                    {% endif %}

                    {% set _operations = _operations|merge([{
                        iban: _iban,
                        date_execution: _operation.dateExecution|date("d/m/Y"),
                        created_by: _operation.createdBy,
                        type: _operation.TypeOperationLbl,
                        details: _operation.details,
                        montant:  _operation.montant ~ ' €',
                    }]) %}
                {% endfor %}

                <tr id="client_{{ client.id }}" class="context-menu-one" data-line_type="client" data-client_id="{{ client.id }}">
                    <td></td>
                    <td>{{ _operations|json_encode() }}</td>
                    <td>{{ client.prenom }}</td>
                    <td>{{ client.nom }}</td>
                    <td>{{ client.email }}</td>
                    <td>{{ client.codePostal}}</td>
                    <td>{{ client.ville}}</td>
                    <td>
                        {% for compte in client.comptes %}
                            {{ compte.iban }}
                            {% if (compte.decouvertAutorise and compte.decouvertMaximum) %}
                                (<span id="compte_{{ compte.id }}" data-line_type="compte" data-client_id="{{ client.id }}" data-compte_id="{{ compte.id }}" data-decouvert_autorise="{{ compte.decouvertAutorise }}" style="color: red;" class="context-menu-one"><i>découvert max: {{ compte.decouvertMaximum }} €</i></span> )
                            {% endif %}
                            {% if (client.comptes|length) %}<br />{% endif %}
                        {% endfor %}
                    </td>
                    <td></td>
                </tr>
            {% endfor %}
            </tbody>

            <tfoot></tfoot>
        </table>

    </div>
    {#<div class="row">
        <span id="oualou1" class="context-menu-one btn btn-neutral" data-id="blabal" data-truc="muche">right click me</span>
    </div>#}



    {#<div id="context-menu" style="display:none;">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <a class="dropdown-item" href="#">Something else here</a>
    </div>#}

    <style>
        /* For small screen */
        .row :nth-child(even){
            background-color: #dcdcdc;
        }
        .row :nth-child(odd){
            background-color: #aaaaaa;
        }

        /* For medium screen */
        @media (min-width: 768px) {
            .row :nth-child(4n), .row :nth-child(4n-1) {
                background: #dcdcdc;
            }
            .row :nth-child(4n-2), .row :nth-child(4n-3) {
                background: #aaaaaa;
            }
        }

        /* For large screen */
        @media (min-width: 992px) {
            .row :nth-child(6n), .row :nth-child(6n-1), .row :nth-child(6n-2) {
                background: #dcdcdc;
            }
            .row :nth-child(6n-3), .row :nth-child(6n-4), .row :nth-child(6n-5) {
                background: #aaaaaa;
            }
        }

        td.details-control {
            background: url('https://datatables.net/examples/resources/details_open.png') no-repeat center center;
            cursor: pointer;
        }

        tr.shown td.details-control {
            background: url('https://datatables.net/examples/resources/details_close.png') no-repeat center center;
        }

    </style>

    <script>
        /* Formatting function for row details - modify as you need */
        function all_clients_table_details_format ( d ) {
            // `d` is the original data object for the row
            if (d == undefined || d.client_operations == undefined || d.client_operations == null || !d.client_operations || d.client_operations == "null"){
                return '<div class="alert alert-danger" role="alert">Aucune information fournie/trouvée</div>';
            }

            var client_operations = JSON.parse(d.client_operations);
            console.log(d.client_operations);
            var _return;

            /*(json_details_demande.hasOwnProperty('iban'))?iban=json_details_demande.iban:iban=null;
            (json_details_demande.hasOwnProperty('beneficiaire'))?beneficiaire=json_details_demande.beneficiaire:beneficiaire=null;
            (json_details_demande.hasOwnProperty('iban_is_ok'))?iban_is_ok=json_details_demande.iban_is_ok:iban_is_ok=false;
            (json_details_demande.hasOwnProperty('matching_compte_found'))?matching_compte_found=json_details_demande.matching_compte_found:matching_compte_found=null;*/

            for (var _operation_index in client_operations){
                console.log(_operation_index);
                var _operation = client_operations[_operation_index];
                _return += '<div class="row">';
                _return += '<div class="col-md-2">'+_operation.iban+'</div>';
                _return += '<div class="col-md-2">'+_operation.date_execution+'</div>';
                _return += '<div class="col-md-2">'+_operation.created_by+'</div>';
                _return += '<div class="col-md-2">'+_operation.type+'</div>';
                _return += '<div class="col-md-2">'+_operation.details+'</div>';
                _return += '<div class="col-md-2">'+_operation.montant+'</div>';
                _return += '</div>';
            }

            return _return;
        }

        var all_clients_table = $('#all_clients').DataTable( {
            scrollCollapse: true,
            "language": {
                "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/French.json"
            },
            dom: 'Bfrtip',
            select:"single",
            responsive: true,
            buttons: [
            ]
            ,"columns": [
                {
                    "data": "empty_col",
                    "className": "details-control",
                    "orderable":      false,
                },
                { "data": "client_operations" },
                { "data": "client_prenom" },
                { "data": "client_nom" },
                { "data": "client_email" },
                { "data": "client_code_postal" },
                { "data": "client_ville" },
                { "data": "client_comptes" },

                {
                    "data": "backoffice_actions_col",
                    "orderable":      false,
                },
            ],
            "columnDefs": [
                {
                    "targets": [ 1 ],
                    "visible": false,
                    "searchable": true
                },
                /*{
                    "targets": [ 3 ],
                    "visible": false
                }*/
            ],
            "order": [[1, 'asc']]
        } );

        $('#all_clients tbody').on('click','td', function (){
            var tr = $(this).closest('tr');
            var row = all_clients_table.row( tr );
            console.log(row.data());

            if ( row.child.isShown() ) {
                row.child.hide();
                tr.removeClass('shown');
            }
            else {
                row.child( all_clients_table_details_format(row.data()) ).show();
                tr.addClass('shown');
            }
        });

        /*$('td').on('contextmenu', function(e) {
            //alert('toto');
            var top = e.pageY - 10;
            var left = e.pageX - 10;

            $("#context-menu").css({
                display: "block",
                border: "1px solid black",
                top: top,
                left: left
            });

            return false;
        }).on("click", function() {
            $("context-menu").hide();
        });

        $("#context-menu a").on("click", function() {
            $(this).parent().hide();
        });*/
    </script>

    <script>
        $(function(){
            $.contextMenu({
                selector: '.context-menu-one',
                build: function($trigger, e) {
                    console.log($trigger);
                    console.log($trigger.attr("id"));

                    var id = false;
                    if ($trigger.attr("id"))
                    {
                        id = $trigger.attr("id");
                    }

                    if (id && $('#'+id).data('line_type'))
                    {
                        var line_type = $('#'+id).data('line_type');
                        //alert(line_type);

                        e.items = {
                        }

                        switch (line_type)
                        {
                            case 'client':
                                var client_id = $('#'+id).data('client_id');
                                //alert('client_id = '+client_id+"\n");
                                e.items = {
                                    "edit_client": {name: "Editer la fiche client", icon: "edit"},
                                    "list_demandes": {name: "Historique des demandes du client.", icon: "edit"},
                                }
                                break;

                            case 'compte':
                                var client_id = $('#'+id).data('client_id');
                                var compte_id = $('#'+id).data('compte_id');
                                var has_decouvert_autorise = $('#'+id).data('decouvert_autorise');
                                //alert('client_id = '+client_id+"\n"+'compte_id='+compte_id+"\n");
                                e.items = {
                                    "edit_client": {name: "Editer la fiche client", icon: "edit"},
                                    "edit_decouvert": {name: "Modifier le découvert autorisé", icon: "edit"},
                                }
                                break;

                            default:
                                break;
                        }
                    }

                    console.log(e);
                    // this callback is executed every time the menu is to be shown
                    // its results are destroyed every time the menu is hidden
                    // e is the original contextmenu event, containing e.pageX and e.pageY (amongst other data)
                    return {
                        callback: function(key, options) {
                            var m = "clicked: " + key;
                            //window.console && console.log(m) || alert(m);
                            switch (key)
                            {
                                case 'edit_client':
                                    document.location.href = "/client/edit/" + client_id;
                                    break;

                                case 'list_demandes':
                                    document.location.href = "/demandes/client/" + client_id;
                                    break;

                                case 'edit_decouvert':
                                    document.location.href = "/decouvert/edit/" + compte_id;
                                    break;
                            }
                            document.location.href
                        },
                        items: e.items
                        /*items: {
                            "edit": {name: "Edit", icon: "edit"},
                            "cut": {name: "Cut", icon: "cut"},
                            "copy": {name: "Copy", icon: "copy"},
                            "paste": {name: "Paste", icon: "paste"},
                            "delete": {name: "Delete", icon: "delete"},
                            "sep1": "---------",
                            "quit": {name: "Quit", icon: function($element, key, item){ return 'context-menu-icon context-menu-icon-quit'; }}
                        }*/
                    };
                }
            });
        });
    </script>

{% endblock %}

templates/backoffice/edit_client.html.twig
{% extends 'backoffice/base.html.twig' %}

{% block title %}Backoffice Banque Dauphine{% endblock %}

{% block navbar %}
    {% include 'backoffice/navbar_authenticated.html.twig' %}
{% endblock %}

{% block body %}

    {% if app.session.flashbag.peek('success')|length > 0 %}
        <div class="alert alert-warning">
            {% for message in app.flashes('success') %}
                {{ message }}<br />
            {% endfor %}
        </div>
    {% else %}
    {% endif %}

    {% if app.session.flashbag.peek('error')|length > 0 %}
        <div class="alert alert-danger">
            {% for message in app.flashes('error') %}
                {{ message }}
            {% endfor %}
        </div>
    {% else %}
    {% endif %}

    <div class="container-fluid" style="padding-top: 55px;">
        <div class="container-fluid bg-grey">
            <div class="container">
                <legend>Editer les informations client</legend>

                {{ form_start(backoffice_client_form) }}

                {{ form_end(backoffice_client_form) }}

            </div>
        </div>
    </div>
{% endblock %}

templates/backoffice/plateforme.html.twig
{% extends 'backoffice/base.html.twig' %}

{% block title %}Backoffice Banque Dauphine{% endblock %}

{% block navbar %}
    {% include 'backoffice/navbar_authenticated.html.twig' %}
{% endblock %}

{% block body %}

    <div class="container-fluid" style="padding-top: 55px;">
        YO
    </div>

{% endblock %}