src/Entity/Comptes.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Blameable\Traits\BlameableEntity;
use Gedmo\IpTraceable\Traits\IpTraceableEntity;
use Gedmo\SoftDeleteable\Traits\SoftDeleteableEntity;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ComptesRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Comptes
{
    use IpTraceableEntity;
    use BlameableEntity;
    use SoftDeleteableEntity;
    use TimestampableEntity;

    const COMPTE_COURANT = "COMPTE_COURANT";
    const COMPTE_EPARGNE = "COMPTE_EPARGNE";
    const COMPTE_JOINT = "COMPTE_JOINT";
    const COMPTE_AGENCE = "COMPTE_AGENCE";
    const COMPTE_BANQUE = "COMPTE_BANQUE";
    const COMPTE_BANK = "COMPTE_BANK";

    const COMPTES_LABELS = [
        self::COMPTE_COURANT => "Compte courant",
        self::COMPTE_EPARGNE => "Compte épargne",
        self::COMPTE_JOINT => "Compte joint",
        self::COMPTE_AGENCE => "Compte agence",
        self::COMPTE_BANQUE => "Compte banque",
        self::COMPTE_BANK => "Compte banque",
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", options={"unsigned"=true}, columnDefinition="INT(11) UNSIGNED ZEROFILL", nullable=true)
     */
    private $num_compte;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $type;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $solde;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $decouvert_autorise;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $decouvert_maximum;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Agences", fetch="EAGER", inversedBy="comptes")
     */
    private $agence_id;


    /**
     * @ORM\Column(type="integer", options={"unsigned"=true}, columnDefinition="INT(2) UNSIGNED ZEROFILL", nullable=true)
     */
    private $cle_rib;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $iban;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Client", fetch="EAGER", inversedBy="comptes")
     */
    private $compte_client_id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CartesBancaires", mappedBy="Compte")
     */
    private $cartesBancaires;

    public function __construct()
    {
        $this->compte_client_id = new ArrayCollection();
        $this->decouvert_autorise = false;
        $this->decouvert_maximum = 0;
        $this->solde = 0;
        $this->cartesBancaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumCompte(): ?int
    {
        return $this->num_compte;
    }

    public function setNumCompte(?int $num_compte): self
    {
        $this->num_compte = $num_compte;
        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function getTypeLbl(): ?string
    {
        return self::COMPTES_LABELS[$this->type];
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getCleRib(): ?int
    {
        return $this->cle_rib;
    }

    public function setCleRib(?int $cle_rib): self
    {
        $this->cle_rib = $cle_rib;
        return $this;
    }

    public function getIban(): ?string
    {
        return $this->iban;
    }

    public function setIban(?string $iban): self
    {
        $this->iban = $iban;

        return $this;
    }

    public function getSolde(): ?float
    {
        return $this->solde;
    }

    public function setSolde(?float $solde): self
    {
        $this->solde = $solde;

        return $this;
    }

    public function getDecouvertAutorise(): ?bool
    {
        return $this->decouvert_autorise;
    }

    public function setDecouvertAutorise(?bool $decouvert_autorise): self
    {
        $this->decouvert_autorise = $decouvert_autorise;

        return $this;
    }

    public function getDecouvertMaximum(): ?int
    {
        return $this->decouvert_maximum;
    }

    public function setDecouvertMaximum(?int $decouvert_maximum): self
    {
        $this->decouvert_maximum = $decouvert_maximum;

        return $this;
    }

    public function getAgenceId(): ?Agences
    {
        return $this->agence_id;
    }

    public function setAgenceId(?Agences $agence_id): self
    {
        $this->agence_id = $agence_id;

        return $this;
    }

    /**
     * @return Collection|Client[]
     */
    public function getCompteClientId(): Collection
    {
        return $this->compte_client_id;
    }

    public function addCompteClientId(Client $compteClientId): self
    {
        if (!$this->compte_client_id->contains($compteClientId)) {
            $this->compte_client_id[] = $compteClientId;
        }

        return $this;
    }

    public function removeCompteClientId(Client $compteClientId): self
    {
        if ($this->compte_client_id->contains($compteClientId)) {
            $this->compte_client_id->removeElement($compteClientId);
        }

        return $this;
    }

    /**
     * @return Collection|CartesBancaires[]
     */
    public function getCartesBancaires(): Collection
    {
        return $this->cartesBancaires;
    }

    public function addCartesBancaire(CartesBancaires $cartesBancaire): self
    {
        if (!$this->cartesBancaires->contains($cartesBancaire)) {
            $this->cartesBancaires[] = $cartesBancaire;
            $cartesBancaire->setCompte($this);
        }

        return $this;
    }

    public function removeCartesBancaire(CartesBancaires $cartesBancaire): self
    {
        if ($this->cartesBancaires->contains($cartesBancaire)) {
            $this->cartesBancaires->removeElement($cartesBancaire);
            // set the owning side to null (unless already changed)
            if ($cartesBancaire->getCompte() === $this) {
                $cartesBancaire->setCompte(null);
            }
        }

        return $this;
    }
}

src/Controller/EspaceClientController.php
<?php

namespace App\Controller;

use App\Entity\Client;
use App\Entity\Comptes;
use App\Entity\Demandes;
use App\Entity\Operations;
use App\Form\ClientEditsProfileType;
use App\Form\ClientMakesOperationType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpKernel\KernelInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Profiler\Profiler;
use Symfony\Component\HttpFoundation\BinaryFileResponse;

class EspaceClientController extends AbstractController
{
    private $em;
    private $request;
    private $appKernel;

    public function __construct(EntityManagerInterface $em, RequestStack $requestStack, KernelInterface $appKernel, Profiler $profiler)
    {
        $request = $requestStack->getCurrentRequest();
        $this->em = $em;
        $this->request = $request;
        $this->appKernel = $appKernel;
        $this->profiler = $profiler;
    }

    /**
     * @Route("/espace/client", name="espace_client")
     */
    public function index()
    {
        $client_user = $this->getUser();
        $client_id = $client_user->getClientId();
        $client = $this->getDoctrine()
            ->getRepository(Client::class)
            ->find($client_id)
        ;
        dump($client);

        $comptes = $client->getComptes();
        dump($comptes);

        return $this->render('espace_client/index.html.twig', [
            'controller_name' => 'EspaceClientController',
            'client' => $client,
            'comptes' => $comptes,
        ]);
    }

    public function detail_compte($compte_id)
    {
        $client_user = $this->getUser();
        $client_id = $client_user->getClientId();
        $client = $this->getDoctrine()
            ->getRepository(Client::class)
            ->find($client_id)
        ;
        $comptes = $client->getComptes();
        foreach ($comptes as $compte)
        {
            if ($compte->getId() == $compte_id) //User is owner of the account
            {
                $operations = $this->getDoctrine()
                    ->getRepository(Operations::class)
                    ->findByCompte($compte);
                dump($operations);

                return $this->render('espace_client/comptes/details.html.twig', [
                    'controller_name' => 'EspaceClientController',
                    'client' => $client,
                    'compte' => $compte,
                    'operations' => $operations,
                ]);
                break;
            }
        }

        return $this->redirectToRoute('clients_logout');
    }

    public function new_virement(EntityManagerInterface $em, Request $request)
    {
        $client_user = $this->getUser();
        $client_id = $client_user->getClientId();
        $client = $this->getDoctrine()
            ->getRepository(Client::class)
            ->find($client_id)
        ;

        $form = $this->createForm(ClientMakesOperationType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            /**
             * @var $operation Operations
             */
            $operation = $form->getData();
            dump($operation);
            if ($operation->getEmetteurCompteId() && $operation->getDestinataireCompteId() == $operation->getEmetteurCompteId())
            {

                $this->addFlash('error', 'Le compte émetteur et le compte destinataire doivent être différents');
                return $this->redirectToRoute('clients_virement_new');
            }


            //dd($operation);
            $operation->setTypeOperation(Operations::TYPE_VIREMENT);
            $operation->setDateExecution( new \DateTime() );
            if ($operation_result = $operation->execute($em))
            {
                $em->persist($operation);
                $this->addFlash('success', 'Votre opération a bien été enregistrée');

                if ($client->getSendSmsNotifications())
                {
                    $nexmo_api_key = getenv('NEXMO_API_KEY');
                    $nexmo_api_secret = getenv('NEXMO_API_SECRET');
                    $nexmo_from = getenv('NEXMO_FROM');
                    //dump($nexmo_api_key);
                    //dump($nexmo_api_secret);

                    $nexmo_client = new \Nexmo\Client(new \Nexmo\Client\Credentials\Basic($nexmo_api_key, $nexmo_api_secret));
                    //dump($nexmo_client);
                    $sms_body_init='Nouvelle opération : '.PHP_EOL;
                    $sms_body=$sms_body_init;
                    /*if ($operation->getCompteEmetteur()->getCompteClientId() == $client->getId())
                    {
                        */$sms_body .= 'débit de '.number_format($operation->getMontant(),2,',',' ').
                            ' € depuis le compte '.$operation->getCompteEmetteur()->getIban().PHP_EOL;
                    /*}*/

                    /*if ($operation->getBeneficiaire()->getCompte()->getCompteClientId() == $client->getId())
                    {
                        */$sms_body .= 'crédit de '.number_format($operation->getMontant(),2,',',' ').
                            ' € sur le compte '.$operation->getBeneficiaire()->getCompte()->getIban().PHP_EOL;
                    /*}*/
                    //dump($sms_body);


                    if ($sms_body != $sms_body_init)
                    {
                        $message = $nexmo_client->message()->send([
                            'to' => $client->getMobile(),
                            'from' => $nexmo_from,
                            'text' => $sms_body,
                        ]);
                    }
                    //dump($message);
                    //dd('Send sms notification');
                }
            }
            else
            {
                $this->addFlash('error', 'Votre opération n\'a pas pu être enregistrée. Vérifiez le solde de votre compte');
            }
            $em->flush();

            return $this->redirectToRoute('clients_virement_new');
            /*unset($form);
            $form = $this->createForm(ClientMakesOperationType::class);

            return $this->render('espace_client/virements/nouveau.html.twig', [
                'operation_result' => $operation_result,
                'controller_name' => 'EspaceClientController',
                'client' => $client,
                'operation' => $operation,
                'client_virement_form' => $form->createView(),
            ]);*/
        }

        return $this->render('espace_client/virements/nouveau.html.twig', [
            'controller_name' => 'EspaceClientController',
            'client' => $client,
            'client_virement_form' => $form->createView(),
        ]);
    }

    public function new_beneficiaire()
    {
        $client_user = $this->getUser();
        $client_id = $client_user->getClientId();
        $client = $this->getDoctrine()
            ->getRepository(Client::class)
            ->find($client_id)
        ;

        return $this->render('espace_client/virements/beneficiaires/nouveau.html.twig', [
            'controller_name' => 'EspaceClientController',
            'client' => $client,
        ]);
    }

    public function commander($article, $confirm)
    {
        $has_demande = $is_success = false;
        $client_user = $this->getUser();
        $client_id = $client_user->getClientId();
        $client = $this->getDoctrine()
            ->getRepository(Client::class)
            ->find($client_id)
        ;

        dump($article);
        dump($confirm);

        $demande = new Demandes($article);
        dump($demande);

        if ($article == 'beneficiaire-virement')
        {
            $datas_request = $this->request->getContent();

            $beneficiaire = $this->request->get('beneficiaire');
            $code_bank = str_pad($this->request->get('code_bank'),5, '0', STR_PAD_LEFT);
            $code_agence = str_pad($this->request->get('code_agence'), 5, '0', STR_PAD_LEFT);
            $num_compte = str_pad($this->request->get('num_compte'), 11, '0', STR_PAD_LEFT);
            $cle_rib = str_pad($this->request->get('cle_rib'), 2, '0', STR_PAD_LEFT);
            $iban = 'FR75'.$code_bank.$code_agence.$num_compte.$cle_rib;

            if ($beneficiaire && $code_agence && $code_bank && $cle_rib && $iban)
            {
                $datas = [
                    'beneficiaire' => $beneficiaire,
                    'code_bank' => $code_bank,
                    'code_agence' => $code_agence,
                    'num_compte' => $num_compte,
                    'cle_rib' => $cle_rib,
                    'iban' => $iban,
                ];
                $demande->setDetails($datas);
                dump($datas);

                //Pas de demande existante, on enregistre la demande
                $client->addDemande($demande);
                $this->em->persist($client);
                $this->em->persist($demande);
                $this->em->flush();
                $this->addFlash('success', 'Nous avons bien enregistré votre demande.');
                $is_success = $has_demande = true;

                return $this->redirectToRoute('clients_demander', ['article' => $article]);
            }
        }


        //Check si une demande a déjà été faite
        $existing_demandes = $this->getDoctrine()
            ->getRepository(Demandes::class)
            ->findByTypeByClient($demande->getType(), $client->getId());

        if (count($existing_demandes))
        {
            $has_demande = true;
        }
        dump($existing_demandes);

        if ($confirm == true && !$has_demande && $article != 'beneficiaire-virement')
        {
            //Pas de demande existante, on enregistre la demande

templates/espace_client/commander/cb.html.twig
{% extends 'base.html.twig' %}

{% block title %}Espace Client{% endblock %}

{% block navbar %}
    {% include 'espace_client/navbar_authenticated.html.twig' %}
{% endblock %}

{% block body %}
    {% block flash_messages %}
        {% include 'espace_client/flash_messages.html.twig' %}
    {% endblock %}

    <div class="container-fluid bg-grey" style="padding-top: 55px;">
        <div class="row">&nbsp;<br />&nbsp;</div>
        {% if ( has_demande ) %}
        <div id="content" style="width: 70%;" class="alert alert-warning">
            Vous avez déjà une demande enregistrée.<br />
            Nous revenons vers vous très prochainement.<br />
        </div>
        {% else %}
        <div id="content" style="width: 70%;">
            <div class="container" style="text-align: center; clear: both; padding-top: 150px;">
                <a href="{{ path('clients_commander_cb', {confirm: true}) }}">
                    <button class="btn btn-warning">Confirmer la demande</button>
                </a>
            </div>
        </div>
        {% endif %}
        </div>
    </div>
{% endblock %}

templates/espace_client/commander/chequier.html.twig
{% extends 'base.html.twig' %}

{% block title %}Espace Client{% endblock %}

{% block navbar %}
    {% include 'espace_client/navbar_authenticated.html.twig' %}
{% endblock %}

{% block body %}
    {% block flash_messages %}
        {% include 'espace_client/flash_messages.html.twig' %}
    {% endblock %}

    <div class="container-fluid bg-grey" style="padding-top: 55px;">
        <div class="row">&nbsp;<br />&nbsp;</div>
        {% if ( has_demande ) %}
            <div id="content" style="width: 70%;" class="alert alert-warning">
                Vous avez déjà une demande enregistrée.<br />
                Nous revenons vers vous très prochainement.<br />
            </div>
        {% else %}
            <div id="content" style="width: 70%;">
                <div class="container" style="text-align: center; clear: both; padding-top: 150px;">
                    <a href="{{ path('clients_commander_chequier', {confirm: true}) }}">
                        <button class="btn btn-warning">Confirmer la demande</button>
                    </a>
                </div>
            </div>
        {% endif %}
    </div>
    </div>

{% endblock %}

templates/espace_client/commander/commande.html.twig
{% extends 'base.html.twig' %}

{% block title %}Espace Client{% endblock %}

{% block navbar %}
    {% include 'espace_client/navbar_authenticated.html.twig' %}
{% endblock %}

{% block body %}
    <style>
        .user-input-wrp {
            position: relative;
            width: 50%;
        }
        .user-input-wrp .inputText{
            width: 200px;
            outline: none;
            border:none;
            border-bottom: 1px solid #777;
        }
        .user-input-wrp .inputText:invalid {
            box-shadow: none !important;
        }
        .user-input-wrp .inputText:focus{
            border-color: blue;
            border-width: medium medium 2px;
        }
        .user-input-wrp .floating-label {
            position: absolute;
            pointer-events: none;
            top: 18px;
            left: 10px;
            transition: 0.2s ease all;
        }
        .user-input-wrp input:focus ~ .floating-label,
        .user-input-wrp input:not(:focus):valid ~ .floating-label{
            top: 0px;
            left: 10px;
            font-size: 13px;
            opacity: 1;
        }
    </style>

    <div class="container-fluid bg-grey" style="padding-top: 55px;">
        {% block flash_messages %}
            {% include 'espace_client/flash_messages.html.twig' %}
        {% endblock %}


        <div class="row">&nbsp;<br />&nbsp;</div>
        {% if ( has_demande and is_success == false and confirm == false and _article != 'beneficiaire-virement' ) %}
        <div id="content" style="width: 70%;" class="alert alert-warning">
            Vous avez déjà une demande enregistrée.<br />
            Nous revenons vers vous très prochainement.<br />
        </div>
        {% elseif confirm == true %}
        {% else %}
            {% if _article == 'beneficiaire-virement' %}
                <div class="row">
                    <form method="POST">
                        <label for="beneficiaire">Bénéficiaire</label>
                        <input type="text" id="beneficiaire" name="beneficiaire" style="width: 250px;"/>

                        <br />

                        <label for="iban">IBAN</label>

                        <table border="0" valign="middle">
                            <tr>
                                <td>
                                    <div class="user-input-wrp">
                                        <br/>
                                        <input type="text" class="inputText" id="code_bank" name="code_bank" required maxlength="5"/>
                                        <span class="floating-label">Code banque</span>
                                    </div>
                                </td>

                                <td valign="middle" style="font-weight: bold;"> - </td>

                                <td>
                                    <div class="user-input-wrp">
                                        <br/>
                                        <input type="text" id="code_agence" name="code_agence" class="inputText" required  maxlength="5"/>
                                        <span class="floating-label">Code agence</span>
                                    </div>
                                </td>

                                <td valign="middle" style="font-weight: bold;"> - </td>

                                <td>
                                    <div class="user-input-wrp">
                                        <br/>
                                        <input type="text" class="inputText" id="num_compte" name="num_compte" required  maxlength="12"/>
                                        <span class="floating-label">Num compte</span>
                                    </div>
                                </td>

                                <td valign="middle" style="font-weight: bold;"> - </td>

                                <td>
                                    <div class="user-input-wrp">
                                        <br/>
                                        <input type="text" class="inputText" id="cle_rib" name="cle_rib" required  maxlength="2"/>
                                        <span class="floating-label">Clé RIB</span>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="7"><br /></td>
                            </tr>
                            <tr>
                                <td><button type="submit" class="btn btn-success">Valider</button></td>
                                <td colspan="6">&nbsp;</td>
                            </tr>
                        </table>


                    </form>
                </div>
            {% else %}
                <div id="content" style="width: 50%; text-align: center;" align="center">
                    <div class="container" style="text-align: center; padding-right: 300px; padding-top: 50px;">
                        <a href="{{ path('clients_demander', {article: _article, confirm: true}) }}">
                            <button class="btn btn-warning">Confirmer la demande : {{ demande.typeLbl }}</button>
                        </a>
                    </div>
                </div>
            {% endif %}
        {% endif %}
        </div>
    </div>
{% endblock %}